# Clean the retail dataset
## Objective
- Convert Date column to datetime
- Check every numeric column has correct numeric datatype
- Check for impossible values
    - Age < 0
    - Quantity < 0
    - Price per Unit < 0
    - Total Amount < 0
- Save the cleaned dataset

## Import Library and set up data

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/retail_sales_dataset.csv")

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

## Convert Date to Datetime

In [3]:
df["Date"] = pd.to_datetime(df["Date"])

In [4]:
df.dtypes

Transaction ID               int64
Date                datetime64[ns]
Customer ID                 object
Gender                      object
Age                          int64
Product Category            object
Quantity                     int64
Price per Unit               int64
Total Amount                 int64
dtype: object

- Here we have successfully converted "Date" to datetime datatype

## Check For Missing Values

In [5]:
df.isna().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

## Check fo Duplicate Values

In [6]:
df.duplicated().sum()

0

## Check For Impossible Values

In [7]:
cols_to_check = ["Age","Quantity","Price per Unit","Total Amount"]

summary = {
    "Columns":cols_to_check,
    "Impossible(<0)": [(df[cols]<=0).sum() for cols in cols_to_check]
}

impossible_summary = pd.DataFrame(summary)

impossible_summary

          Columns  Impossible(<0)
0             Age               0
1        Quantity               0
2  Price per Unit               0
3    Total Amount               0

- Here hwe have found out that all numerical values do not have any impossible values

## Saving the cleaned dataset

In [10]:
df.to_csv("../data/processed/retail_sales_cleaned.csv",index=False)
df.dtypes

Transaction ID               int64
Date                datetime64[ns]
Customer ID                 object
Gender                      object
Age                          int64
Product Category            object
Quantity                     int64
Price per Unit               int64
Total Amount                 int64
dtype: object

## Conclusion
- So we have found out that there is no missing and duplicate values
- Also there were not impossible value for the numerical columns
- As there was "Date" in type object we have converted it into "datetime" datatype
- Andd also data has been cleaned and saved